delete nyhs/pr144_pictorial_lettersheet.xml
delete nyhs/pr144_pictorial_lettersheet.xml because there is a
  trailing space in the EADID:
  error: invalid <eadid> "pr144_pictorial_lettersheet "